config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  resources :projects do
    resources :bugs, except: [:destroy] do
      member do
        get :assign_bug
        get :resolve_bug
      end
    end
  end

  root to: 'projects#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bug.rb
# frozen_string_literal: true

class Bug < ApplicationRecord
  has_one_attached :image, dependent: :destroy

  belongs_to :user
  belongs_to :project

  enum bug_type: { feature: 0, bug: 1 }
  enum status: { created: 0, started: 1, completed: 2, resolved: 3 }

  validates :status, :bug_type, presence: true
  validates :title, presence: true, uniqueness: { scope: :project_id, message: 'same bug exists for this project.' }
  validate :image_type

  def bug_owner?(id)
    user_id == id
  end

  private

  def image_type
    return if image.content_type.in?(%('image/gif image/png'))

    errors.add(:image, 'needs to be a gif or png!')
  end
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  has_many :user_projects, dependent: :destroy
  has_many :users, through: :user_projects
  has_many :bugs, dependent: :destroy

  belongs_to :creator, inverse_of: :owned_projects, class_name: 'User'

  validates :title, presence: true

  def project_owner?(id)
    creator_id == id
  end

  # def manager
  #   users.find_by(user_type: 'manager')
  # end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # include ApplicationConstants::User

  enum user_type: { manager: 0, dev: 1, qa: 2 }

  has_many :user_projects, dependent: :destroy
  has_many :projects, through: :user_projects
  has_many :bugs, dependent: :destroy
  has_many :owned_projects, inverse_of: :creator, foreign_key: :creator_id, dependent: :destroy, class_name: 'Project'

  validates :name, :user_type, presence: true
  validates :name, length: { minimum: 2 }

  scope :developers, -> { where(user_type: 'dev') }
  scope :testers, -> { where(user_type: 'qa') }
end

app/models/user_project.rb
# frozen_string_literal: true

class UserProject < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit::Authorization
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  rescue_from ActiveRecord::RecordNotFound, with: :id_record_not_found

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name user_type])
  end

  private

  def user_not_authorized
    flash[:alert] = I18n.t('authorization.not_authorized')
    redirect_back(fallback_location: root_path)
  end

  def id_record_not_found
    flash[:error] = I18n.t('authorization.not_authorized')
    redirect_to(root_path)
  end
end

app/controllers/bugs_controller.rb
# frozen_string_literal: true

class BugsController < ApplicationController
  before_action :set_bug, only: %i[show edit update assign_bug resolve_bug]
  before_action :set_project, only: %i[index show new create edit update]
  before_action :validate_bug, only: %i[edit update]

  def index
    @bugs = @project.bugs.includes(image_attachment: :blob)
  end

  def show; end

  def new
    @bug = @project.bugs.build
    authorize @bug
  end

  def create
    @bug = @project.bugs.build(bug_params)
    @bug.user = current_user

    if @bug.save!

      redirect_to project_bug_path(@project, @bug), notice: I18n.t('bug.created')
    else
      render :new
    end
  end

  def edit; end

  def assign_bug
    flash[:notice] = if @bug.update!(dev_id: current_user.id, status: :started)
                       I18n.t('bug.assign_bug')
                     else
                       I18n.t('bug.assign_bug_failed')
                     end
    redirect_to :projects
  end

  def resolve_bug
    flash[:notice] = if @bug.resolved!
                       I18n.t('bug.resolve_bug')
                     else
                       I18n.t('bug.resolve_bug_failed')
                     end
    redirect_to :projects
  end

  def update
    if @bug.update(bug_params)
      redirect_to project_bug_path(@project, @bug)
    else
      render :edit
    end
  end

  private

  def validate_bug
    authorize @bug
  end

  def set_bug
    @bug = Bug.find(params[:id])
  end

  def bug_params
    params.require(:bug).permit(:title, :deadline, :bug_type, :image, :status)
  end

  def set_project
    @project = Project.find(params[:project_id])
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show edit update destroy]
  before_action :set_users, only: %i[new edit]
  before_action :validate_project, only: %i[edit update destroy]

  def index
    @projects = policy_scope(Project)
  end

  def show; end

  def new
    @project = Project.new
    authorize @project
  end

  def create
    @project = current_user.owned_projects.new(project_params)

    if @project.save!
      flash[:notice] = I18n.t('project.created')
      redirect_to @project
    else
      render :new
    end
  end

  def edit; end

  def update
    if @project.update!(project_params)
      redirect_to @project
    else
      render :edit
    end
  end

  def destroy
    redirect_to projects_path if @project.destroy!
  end

  private

  def validate_project
    authorize @project
  end

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title, :description, user_ids: [])
  end

  def set_users
    @developers = User.developers
    @testers = User.testers
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/bugs_helper.rb
# frozen_string_literal: true

module BugsHelper
  def bug_types
    Bug.bug_types.map { |key, _value| [key.capitalize, key] }
  end
end

app/helpers/projects_helper.rb
# frozen_string_literal: true

module ProjectsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def select_user_type
    User.user_types.map { |key, _value| [key.capitalize, key] }
  end
end

app/views/bugs/_bug.html.erb
<tr>
  <td><%= bug.title %></td>
  <td><%= bug.deadline %></td>
  <td><%= image_tag(bug.image, alt: "No image", class: "bug-image-style") if bug.image %></td>
  <td><%= bug.bug_type %></td>
  <td><%= bug.project.title %></td>
  <td><%= bug.status %></td>
  <td><%= link_to 'Show', project_bug_path(project, bug) %></td>
</tr>

app/views/bugs/_form.html.erb
<%= form_with model: [@project, @bug], local: true do |form| %>

 <% if @bug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bug.errors.count, "error") %> prohibited this bug from being saved:</h2>

      <ul>
        <% @bug.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :deadline %><br>
    <%= form.date_field :deadline, min: Date.tomorrow %>
  </p>

   <p>
    <%= form.label :image %><br>
    <%= form.file_field :image %>
  </p>

  <p>
    <% form.label :bug_type %><br />
    <%= form.select :bug_type, bug_types%>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/bugs/edit.html.erb
<h1>Editing Bug</h1>
<br/>
<%= render 'form', bug: @bug %>

<br/>

<%= link_to 'Back', project_bug_path %>

app/views/bugs/index.html.erb
<h1>Bugs of Project</h1>

<table>
  <tr>
    <th>Descriptive Title</th>
    <th>Deadline</th>
    <th>Image</th>
    <th>Bug Type</th>
    <th>Bug Project</th>
    <th>Status</th>

    <th></th>
  </tr>

  <%= render @bugs, project: @project %>

</table>

 <td><%= link_to 'Back', projects_path %></td>

app/views/bugs/new.html.erb
<h1>Add New Bug</h1>
<br/>
 
<%= render 'form', bug: @bug %>

<br/>

app/views/bugs/show.html.erb
<p>
  <strong>Bug Title:</strong>
  <%= @bug.title %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @bug.deadline %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@bug.image.variant(resize:"500x500"), alt: "No image") if @bug.image %>
</p>

<p>
  <strong>Bug Type</strong>
  <%= @bug.bug_type %>
</p>

<p>
  <strong>Project having bug:</strong>
  <%= @bug.project.title %>
</p>

<p>
  <strong>Bug status:</strong>
  <%= @bug.status %>
</p>


<% if policy(@bug).assign_bug? %>
  <% if current_user.id == @bug.dev_id %>
    <%= link_to 'Resolve Bug', resolve_bug_project_bug_path(@bug.id), class: "btn btn-success form-control" %>

  <% else %>
    <%= link_to 'Assign Bug', assign_bug_project_bug_path(@bug.id), class: "btn btn-primary form-control" %><br/>
  <% end %>
<% else %>

<%end%>

  <% if policy(@bug).edit? %>
    <%= link_to 'Edit', edit_project_bug_path(@project,@bug) %> |
  <% end %>
<%= link_to 'Back', project_bugs_path %>

app/views/layouts/_alerts.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="mx-5 alert-dismissible fade show alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Bugzilla</title>

     <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'%>
    <%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css", "application" %>
    <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js", "application" %>
  </head>
  <body>

    <%= render 'users/header' %>
    <div class=container>

    <br/>

    <%= render 'layouts/alerts' %>

    <%= yield %>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with model: @project, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title, required: true %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <%= render partial:'projects/selectusers',locals: {project: @project, users: @developers} %>

  <%= render partial:'projects/selectusers', locals: {project: @project, users: @testers} %>
  
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/projects/_project.html.erb
<tr>
<td>
<%= link_to project.title, project %>
</td>

<td><%= project.description %></td>
<td><%= link_to 'All bugs', project_bugs_path(project),class: "btn btn-outline-danger btn-sm" %></td>
  <% if current_user.qa? %>
    <td><%= link_to 'Add bugs', new_project_bug_path(project),class: "btn btn-outline-danger btn-sm" %></td>
  <% end %>
</tr>

app/views/projects/_selectusers.html.erb
 <div class="field">
    <%= hidden_field_tag "project[user_ids][]", nil %>
    <% users.each do |user| %>
      <%= check_box_tag "project[user_ids][]",user.id, @project.user_ids.include?(user.id),id: dom_id(user) %>
      <%= label_tag dom_id(user), user.name%><br>
    <% end %>
 </div>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>
<br/>
<%= render 'form', project: @project %>

<br/>

<%= link_to 'Back', project_path %>

app/views/projects/index.html.erb
<h1>List of Projects</h1>

<% if user_signed_in? %>
  <table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Title</th>
        <th>Description</th>

        <th>Show Bugs</th>
        <th> </th>
      </tr>
    </thead>

    <tbody>
          <%= render @projects %>
    </tbody>
  </table>

  <br>

  <% if policy(@projects).new? %>
    <%= link_to 'New Project', new_project_path, class:"btn btn-secondary" %>
  <% end %>
<% end %>

app/views/projects/new.html.erb
<h1>Add New Project</h1>
<br/>
<%= render 'form', project: @project %>

<br/>

app/views/projects/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
    <%= @project.title %>
  </h1>

  <h4 class="display-7">
    <%= @project.description%>
  </h4>

  <% if policy(@project).edit? %>
    <%= link_to 'Edit', edit_project_path(@project) %> |
  <% end %>

  <% if policy(@project).destroy? %>
    <%= link_to 'Delete', @project, method: :delete, data: { confirm:  I18n.t('project.sure_message') }, class: "btn btn-danger" %>
  <% end %>

  <%= link_to 'Back', projects_path %>
</div>

app/views/users/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Bugzilla', root_path, class: "navbar-brand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <% if user_signed_in? %>

        <li class="nav-item">
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
         <%=link_to 'Projects', projects_path, :class=>'nav-link' %>
        </li>

      <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
        </li>
      <% end %>


      <% if user_signed_in? %>
        <li class="navbar-brand"><%= current_user.name.upcase_first %> <%= current_user.user_type.upcase_first %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/users/index.html.erb
<h1>Welcome To Bugzilla</h1>